# Generated by Django 5.2.5 on 2025-08-26 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Malumot Nomi')),
                ('description', models.TextField(verbose_name='Malumot qo`shing')),
                ('views', models.IntegerField(default=0, verbose_name='Ko`rishlar soni')),
                ('price', models.IntegerField(verbose_name='Ko`rishlar Soni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Surat kiriting')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='video kiriting')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Qo`yilgan vaqti')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='O`zgartirilgan Vaqti')),
                ('published', models.BooleanField(default=True, verbose_name='Belgilasanggiz Sayitga chiqariladi.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.advertisement', verbose_name='Bo`limlar')),
            ],
            options={
                'verbose_name': 'Elon',
                'verbose_name_plural': 'Elonlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Izox Matin uchun')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan Vaqti')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.announcement', verbose_name='Film')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created'],
            },
        ),
    ]
