# Generated by Django 5.2.5 on 2025-08-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ko`rishlar soni'),
        ),
    ]
