# Generated by Django 5.1.6 on 2025-08-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_announcement_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='price',
        ),
    ]
